// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrizrpjpjpqolculmckf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyaXpycGpwanBxb2xjdWxtY2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3Njg4NzQsImV4cCI6MjA2MDM0NDg3NH0.q8IhEstL9gcbxwZdx0Czwn9jbiCYnJSCqyCiODs42cc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);